[tool.poetry]
name = "mc-ecpe"
version = "0.1.0"
description = ""
authors = ["teostereciu <teostereciu@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^1.26.4"
pandas = "^2.2.1"
jupyter = "^1.0.0"
ipykernel = "^6.29.3"
matplotlib = "^3.8.3"
moviepy = "^1.0.3"
ffmpeg-python = "^0.2.0"
ffmpeg = "^1.4"
pydub = "^0.25.1"
contractions = "^0.1.73"
nltk = "^3.8.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
